name: Build and Deploy Vue Application to Github Pages
on:
  push:
    branches:
    - master
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: npm install, build
      run: |
        cd front-end
      shell: bash
