// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GlobalLayout: typeof import('./src/components/GlobalLayout.vue')['default']
  }
}

export { }
