// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    GlobalLayout: typeof import('./src/components/GlobalLayout.vue')['default']
  }
}

export { }
