name: Build and Deploy Vue Application to Github Pages
on:
  push:
    branches:
    - master
    - main
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: npm install, build
      run: |
        pwd
        cd front-end
        pwd
        npm install
        npm run build
    - name: Create gh-pages
      run: |
            cd front-end
            cd dist
            ln -s index.html 404.html
            git config --global user.email "action@example.com"
            git config --global user.name "action"
            git init
            git add .
            git commit -m 'update'
            git push -f https://Jkssns:${{ secrets.GITHUB_TOKEN }}@github.com/Jkssns/node-app.git master:gh-pages
      shell: bash
